// Copies the single-file bundle into the BetterTouchTool source tree so it ships inside BTT.app and can be
// loaded from Run Real JavaScript with require("bettertouchtool"). Run after `npm run build`.
import { copyFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const src = resolve("dist/bettertouchtool.btt.cjs");
const dest = process.env.BTT_SRC
  ? resolve(process.env.BTT_SRC, "Code/JavaScriptCoreRunner/Modules/bettertouchtool.cjs")
  : resolve("../BetterTouchTool/Code/JavaScriptCoreRunner/Modules/bettertouchtool.cjs");
if (!existsSync(src)) throw new Error(`missing ${src} – run npm run build first`);
const version = JSON.parse(readFileSync("package.json", "utf8")).version;
const banner = `// bettertouchtool ${version} – bundled copy for BetterTouchTool's JavaScript engine (require("bettertouchtool")).\n// Generated by scripts/sync-to-btt.mjs from https://github.com/folivoraAI/bettertouchtool-js – do not edit.\n`;
const body = readFileSync(src, "utf8");
copyFileSync(src, dest);
import("node:fs").then((fs) => fs.writeFileSync(dest, banner + body));
console.log(`copied ${(body.length / 1024).toFixed(0)} KB → ${dest}`);
